# Don't print a new line at the start of the prompt
add_newline = false

# A minimal left prompt
#format = """$all"""

format = """
[î‚¶](#4c2889)\
$kubernetes\
[î‚°](#4c2889 bg:#7928ca)\
$directory\
[î‚°](fg:#7928ca bg:#8a63d2 )\
$git_branch\
[î˜¡](fg:#fdf6e3 bg:#8a63d2)\
$git_status\
[î‚°](fg:#8a63d2 bg:#0761d1)\
$golang\
$nodejs\
$rust\
$swift\
[î‚°](fg:#0761d1 bg:#0070f3)\
$docker_context\
[î‚°](fg:#0070f3 bg:#3291ff)\
$aws\
[î˜¡](fg:#fdf6e3 bg:#3291ff)\
$gcloud\
$terraform\
[î‚°](fg:#3291ff)\
$fill $cmd_duration
$character
"""

# move the rest of the prompt to the right
# right_format = """$all"""

# Replace the "â¯" symbol in the prompt with "Î›"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[Î»](bold green) "
error_symbol = "[Ï‡](bold red) "
vicmd_symbol = "[V](bold green) "

# [git_status]
# format = '([îœˆ \[$all_status$ahead_behind\]]($style) )'
# ahead = "${count}ï•œ"
# diverged = "â‡•${behind_count}ï•„ ${ahead_count}ï•œ"
# behind = "${count}ï•„"
# modified = "${count}ï„ "
# staged = "${count}ï‘— "

[kubernetes]
symbol = "â˜¸ "
style = "bg:#4c2889 fg:#fdf6e3"
format = '[$symbol$context(\($namespace\)) ]($style)'
disabled = false
[kubernetes.context_aliases]
"gke_.*_(?P<var_cluster>[\\w-]+)" = "$var_cluster"

[directory]
style = "bg:#7928ca fg:#fdf6e3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[docker_context]
symbol = "ïŒˆ "
style = "bg:#0070f3"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = "ï˜"
style = "bg:#8a63d2 fg:#fdf6e3"
# truncation_length = 7
truncation_symbol = "â€¦/"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:#8a63d2 fg:#fdf6e3"
ahead = "${count}ï•œ"
diverged = "â‡•${behind_count}ï•„ ${ahead_count}ï•œ"
behind = "${count}ï•„"
modified = "${count}ï„ "
staged = "${count}ï‘— "
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = "î˜§ "
style = "bg:#0761d1 fg:#fdf6e3"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#0761d1 fg:#fdf6e3"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#0761d1 fg:#fdf6e3"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#0761d1 fg:#fdf6e3"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[swift]
symbol = "ï¯£ "

[aws]
symbol = "îŒ½ "
style = "bg:#3291ff fg:#fdf6e3"
format = '[ $symbol$region]($style)'

[gcloud]
symbol = "î² "
style = "bg:#3291ff fg:#fdf6e3"
format = "[ $symbol$account ]($style)"

[terraform]
style = "bg:#3291ff fg:#fdf6e3"
format = "[ğŸğŸ’¨ $version$workspace ]($style)"

[cmd_duration]
min_time = 100
format = "[î‚¶](fg:black)[îƒ $duration](bold bg:black fg:white)[î‚´](fg:black)"

[fill]
symbol = " "

