# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 1200 # ms
continuation_prompt = "â–¶â–¶"
# A minimal left prompt
#format = """$all"""

format = """
[î‚¶](#26235B)\
$kubernetes\
[î‚°](#26235B bg:#812878)\
$directory\
[î‚°](fg:#812878 bg:#A22160 )\
$git_branch\
[î˜¡](fg:#fdf6e3 bg:#A22160)\
$git_status\
[î‚°](fg:#A22160 bg:#CC2336)\
$golang\
$nodejs\
$rust\
$swift\
[î‚°](fg:#CC2336 bg:#E4682A)\
$gcloud\
[î‚°](fg:#E4682A bg:#F69824)\
$aws\
$terraform\
[î‚´](fg:#F69824)\
$fill $cmd_duration
${custom.waypoint}â””â”€ $character
"""

# [î˜¡](fg:#fdf6e3 bg:#F69824)\
# move the rest of the prompt to the right
# right_format = """$all"""

# Replace the "â¯" symbol in the prompt with "Î›"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[Î»](bold green)"
error_symbol = "[Ï‡](bold red)"
vicmd_symbol = "[V](bold green)"

# [git_status]
# format = '([îœˆ \[$all_status$ahead_behind\]]($style) )'
# ahead = "${count}ï•œ"
# diverged = "â‡•${behind_count}ï•„ ${ahead_count}ï•œ"
# behind = "${count}ï•„"
# modified = "${count}ï„ "
# staged = "${count}ï‘— "

[kubernetes]
symbol = "â˜¸ "
style = "bg:#26235B fg:#fdf6e3"
format = '[$symbol$context(\($namespace\)) ]($style)'
disabled = false
[kubernetes.context_aliases]
"gke_.*_(?P<var_cluster>[\\w-]+)" = "$var_cluster"

[directory]
style = "bg:#812878 fg:#fdf6e3"
format = "[ î—¿ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ï˜"
style = "bg:#A22160 fg:#fdf6e3"
# truncation_length = 7
truncation_symbol = "â€¦/"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:#A22160 fg:#fdf6e3"
ahead = "${count}ï•œ"
diverged = "â‡•${behind_count}ï•„ ${ahead_count}ï•œ"
behind = "${count}ï•„"
modified = "${count}ï„ "
staged = "${count}ï‘— "
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = "î˜§"
style = "bg:#CC2336 fg:#fdf6e3"
format = '[ $symbol $version ]($style)'

[java]
symbol = "î‰– "
style = "bg:#CC2336 fg:#fdf6e3"
format = '[ $symbol $version ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#CC2336 fg:#fdf6e3"
# style = "bg:#303030 fg:#68A063 bold"
format = '[ $symbol $version ]($style)'

[rust]
symbol = "î¨"
style = "bg:#CC2336 fg:#fdf6e3"
format = '[ $symbol $version ]($style)'

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[swift]
symbol = "ï¯£ "

[aws]
symbol = "îŒ½ "
style = "bg:#F69824 fg:#fdf6e3"
format = '[ $symbol$region ]($style)'

[gcloud]
symbol = "î² "
style = "bg:#E4682A fg:#fdf6e3"
format = '[ $symbol$account($region)]($style)'

[terraform]
style = "bg:#F69824 fg:#fdf6e3"
format = "[ğŸğŸ’¨ $version$workspace ]($style)"

[cmd_duration]
min_time = 100
format = "[î‚¶](fg:black)[îƒ $duration](bold bg:black fg:white)[î‚´](fg:black)"

[fill]
symbol = " "

[custom.waypoint]
detect_files = ["waypoint.hcl"]
command = """
waypoint status -json \
| jq -r '
    [
        { Name: .Project.Name, App:.Applications[].App, Release: .Applications[].ReleaseStatus }
        | to_entries[]
        | [ .key, .value ]
        | join(": ")
    ]
    | join(" î˜¡ ")'
"""
symbol = "wp"
style = "fg:#14c6cb bg:#252937"
format = "â”œâ”€ [î‚¶](fg:#252937)[$symbol î˜¡ $output]($style)[î‚´](fg:#252937)\n"

